### ISSUE TITLE
erm, what the sigma?

### ISSUE THREAD

**Issue by blok25** [hucario/globia-links#1]

**Comment by hucario** [comment]
This was the placeholder I had for Globia's website back before I think I was even staff? Maybe just a Helper? Either way, deprecated in favor of the [current site](https://github.com/globiamc/website)

**Comment by hucario** [comment]
For idle curiosity's sake, this is what it used to look like:
![image](https://github.com/hucario/globia-links/assets/50851047/ae5817a2-7058-42f1-a35e-13a4f3476aa6)
